### ISSUE TITLE
[Roadmap] Improve user experience

### ISSUE THREAD

**Issue by dandansamax** [camel-ai/crab#7]
## Documents

- [ ] Polish docstrings in crab core
- [ ] Write "Get Start" for developers

## Examples

- [ ] Add benchmark examples in jupyter notebook

## Developing environment

- [ ] Pack environments as docker/k8s services
